In [1]:
import pandas as pd

In [2]:
train_df=pd.read_csv("../data/raw_data/train.tsv",sep='\t')
dev_df=pd.read_csv("../data/raw_data/dev.tsv",sep='\t')

In [3]:
train_df["Label"].value_counts(normalize=True)

Label
moderate          0.676977
not depression    0.221685
severe            0.101338
Name: proportion, dtype: float64

In [4]:
dev_df["Label"].value_counts(normalize=True)

Label
moderate          0.512900
not depression    0.407028
severe            0.080071
Name: proportion, dtype: float64

In [5]:
test_df=pd.read_csv("../data/raw_data/test.tsv",sep='\t')
test_df['Class labels'].value_counts(normalize=True)

Class labels
moderate          0.668413
not depression    0.261325
severe            0.070262
Name: proportion, dtype: float64

In [6]:
test_df

,Pid,text data,Class labels
0,test_pid_1,Im scared : This is it. I lie to myself every ...,moderate
1,test_pid_2,New to this but just wanted to vent : I just f...,moderate
2,test_pid_3,I’m sad : It’s kinda always been an issue. I w...,moderate
3,test_pid_4,Lonely but not alone. : All of my immediately ...,moderate
4,test_pid_5,This year has been trash. : I dont know why I’...,moderate
...,...,...,...
3240,test_pid_3241,"Feeling lonely. : Hi reddit, I haven’t posted ...",severe
3241,test_pid_3242,When would suicide be right? : So I got back f...,severe
3242,test_pid_3243,Lowest I’ve ever been ever. : To make a long s...,severe
3243,test_pid_3244,Does the Toxoplasma Gondii ruined my life ? (f...,severe
3244,test_pid_3245,Getting the correct diagnosis : Currently goin...,severe

In [7]:
train_df

,PID,Text_data,Label
0,train_pid_1,Waiting for my mind to have a breakdown once t...,moderate
1,train_pid_2,My new years resolution : I'm gonna get my ass...,moderate
2,train_pid_3,New year : Somone else Feeling like 2020 will ...,moderate
3,train_pid_4,"My story I guess : Hi, Im from Germany and my ...",moderate
4,train_pid_5,Sat in the dark and cried myself going into th...,moderate
...,...,...,...
8886,train_pid_8887,Ways to reverse memory loss from depression? :...,severe
8887,train_pid_8888,A Comprehensive Guide To Slowly Getting Better...,severe
8888,train_pid_8889,I don’t think college is right for me : TW: su...,severe
8889,train_pid_8890,Please help: Severe insomnia affecting me in m...,severe
8890,train_pid_8891,With each passing day my depression is getting...,severe

In [8]:
dev_df

,PID,Text data,Label
0,dev_pid_1,"I enjoyed today, and I still am! Tomorrows dep...",moderate
1,dev_pid_2,I sorta tried to kill myself : I had a total b...,moderate
2,dev_pid_3,Best suicide method? : I like it quick and eas...,moderate
3,dev_pid_4,a story : I remember the time I'd get on my 3D...,moderate
4,dev_pid_5,The world only cares about beautiful people : ...,moderate
...,...,...,...
4491,dev_pid_4492,Aren’t we all just tired? : I’ve been depresse...,severe
4492,dev_pid_4493,NEED HELP COPING : I had my life pretty much f...,severe
4493,dev_pid_4494,Qutting Zoloft Cold Turkey : I was on 75 mg se...,severe
4494,dev_pid_4495,Crying : I’m coming off my antidepressants and...,severe
4495,dev_pid_4496,Seeking for advice on how to overcome and deal...,severe

In [9]:
dev_df = dev_df.rename(columns={"Text data": "Text_data"})

In [10]:
combined_df = pd.concat([train_df, dev_df], ignore_index=True)
combined_df

,PID,Text_data,Label
0,train_pid_1,Waiting for my mind to have a breakdown once t...,moderate
1,train_pid_2,My new years resolution : I'm gonna get my ass...,moderate
2,train_pid_3,New year : Somone else Feeling like 2020 will ...,moderate
3,train_pid_4,"My story I guess : Hi, Im from Germany and my ...",moderate
4,train_pid_5,Sat in the dark and cried myself going into th...,moderate
...,...,...,...
13382,dev_pid_4492,Aren’t we all just tired? : I’ve been depresse...,severe
13383,dev_pid_4493,NEED HELP COPING : I had my life pretty much f...,severe
13384,dev_pid_4494,Qutting Zoloft Cold Turkey : I was on 75 mg se...,severe
13385,dev_pid_4495,Crying : I’m coming off my antidepressants and...,severe
13386,dev_pid_4496,Seeking for advice on how to overcome and deal...,severe

In [11]:
combined_df["Label"].value_counts(normalize=True)

Label
moderate          0.621872
not depression    0.283932
severe            0.094196
Name: proportion, dtype: float64

In [12]:
conflicting_texts = (
    combined_df
    .groupby("Text_data")["Label"]
    .nunique()
)
conflicting_texts = conflicting_texts[conflicting_texts > 1].index

In [13]:
conflicting_df = combined_df[combined_df["Text_data"].isin(conflicting_texts)].copy()
non_conflicting_df = combined_df[~combined_df["Text_data"].isin(conflicting_texts)].copy()

In [14]:
conflicting_df.sort_values(by="Text_data")

,PID,Text_data,Label
5564,train_pid_5565,"""why don't you talk about how you feel?"" Ok he...",moderate
12521,dev_pid_3631,"""why don't you talk about how you feel?"" Ok he...",not depression
8583,train_pid_8584,(UK) Can I get sectioned if I ‘m not a danger ...,severe
12404,dev_pid_3514,(UK) Can I get sectioned if I ‘m not a danger ...,not depression
3404,train_pid_3405,1/1/20. I’m really really hurting today. : The...,moderate
...,...,...,...
8340,train_pid_8341,numb : i’m thinking about killing my self on m...,severe
5571,train_pid_5572,"show of hands, or am i the only one : i write ...",moderate
12532,dev_pid_3642,"show of hands, or am i the only one : i write ...",not depression
5520,train_pid_5521,something i've wrote a few minutes ago : and s...,moderate
12463,dev_pid_3573,something i've wrote a few minutes ago : and s...,not depression

In [15]:
non_conflicting_df

,PID,Text_data,Label
0,train_pid_1,Waiting for my mind to have a breakdown once t...,moderate
1,train_pid_2,My new years resolution : I'm gonna get my ass...,moderate
2,train_pid_3,New year : Somone else Feeling like 2020 will ...,moderate
3,train_pid_4,"My story I guess : Hi, Im from Germany and my ...",moderate
4,train_pid_5,Sat in the dark and cried myself going into th...,moderate
...,...,...,...
13382,dev_pid_4492,Aren’t we all just tired? : I’ve been depresse...,severe
13383,dev_pid_4493,NEED HELP COPING : I had my life pretty much f...,severe
13384,dev_pid_4494,Qutting Zoloft Cold Turkey : I was on 75 mg se...,severe
13385,dev_pid_4495,Crying : I’m coming off my antidepressants and...,severe
13386,dev_pid_4496,Seeking for advice on how to overcome and deal...,severe

In [16]:
clean_df = non_conflicting_df.drop_duplicates(subset=["Text_data"],keep="first").copy()

In [17]:
clean_df

,PID,Text_data,Label
0,train_pid_1,Waiting for my mind to have a breakdown once t...,moderate
1,train_pid_2,My new years resolution : I'm gonna get my ass...,moderate
2,train_pid_3,New year : Somone else Feeling like 2020 will ...,moderate
3,train_pid_4,"My story I guess : Hi, Im from Germany and my ...",moderate
4,train_pid_5,Sat in the dark and cried myself going into th...,moderate
...,...,...,...
13382,dev_pid_4492,Aren’t we all just tired? : I’ve been depresse...,severe
13383,dev_pid_4493,NEED HELP COPING : I had my life pretty much f...,severe
13384,dev_pid_4494,Qutting Zoloft Cold Turkey : I was on 75 mg se...,severe
13385,dev_pid_4495,Crying : I’m coming off my antidepressants and...,severe
13386,dev_pid_4496,Seeking for advice on how to overcome and deal...,severe

In [18]:
overlap = set(clean_df["Text_data"]) & set(test_df["text data"])
print("Duplicates / overlap:", len(overlap))

Duplicates / overlap: 3

In [19]:
duplicate_df = clean_df[clean_df['Text_data'].isin(overlap)].copy()
duplicate_df

,PID,Text_data,Label
5712,train_pid_5713,Its over : [removed],moderate
7892,train_pid_7893,Does anyone else feel this way? : [removed],not depression
8199,train_pid_8200,i want to die. : [removed],severe

In [20]:
clean_df = clean_df[ ~clean_df["Text_data"].isin(overlap)].copy()

In [21]:
clean_df.to_csv("../data/processed_data/cleaned_data.csv")
conflicting_df.to_csv("../data/processed_data/confliciting_data.csv")